package install

import (
	"fmt"
	"strings"
)

// Phase is a stage of the installation. The script announces each one on the
// serial console so march can report progress.
type Phase string

const (
	PhaseTools      Phase = "tools"
	PhasePartition  Phase = "partition"
	PhaseBase       Phase = "base"
	PhaseDesktop    Phase = "desktop"
	PhaseConfigure  Phase = "configure"
	PhaseBootloader Phase = "bootloader"
)

// Phases lists the stages in the order the script runs them.
var Phases = []Phase{
	PhaseTools, PhasePartition, PhaseBase, PhaseDesktop, PhaseConfigure, PhaseBootloader,
}

// Label is a human-readable description of a phase.
func (p Phase) Label() string {
	switch p {
	case PhaseTools:
		return "Preparing the installer"
	case PhasePartition:
		return "Partitioning the disk"
	case PhaseBase:
		return "Installing the base system"
	case PhaseDesktop:
		return "Installing the desktop"
	case PhaseConfigure:
		return "Configuring the system"
	case PhaseBootloader:
		return "Installing the bootloader"
	}
	return string(p)
}

// Console markers. march watches for these in the guest's serial output.
const (
	MarkerPhase    = "===MARCH:PHASE:"
	MarkerComplete = "===MARCH:COMPLETE==="
	MarkerFailed   = "===MARCH:FAILED==="
)

// baseKernel is Arch Linux ARM's aarch64 kernel. The plain "linux" package
// does not exist in the ALARM repositories.
const baseKernel = "linux-aarch64"

// vulkanPackages give the guest a Vulkan driver for the virtio GPU. They are
// only installed when the host forwards Vulkan through Venus; without that
// forwarding the driver finds no device and Vulkan programs fail more
// confusingly than if it were simply absent.
//
// This is what gets Chromium off its software rasterizer: the browser renders
// through ANGLE, whose backend is Vulkan, so a guest with GL but no Vulkan
// runs its desktop on the GPU and its web pages on the CPU.
//
// Only the driver is here. The loader comes with the browser (chromePackages),
// because Chrome looks for it whether or not the host forwards Vulkan, and a
// loader with no driver behind it simply reports no devices.
var vulkanPackages = []string{"vulkan-virtio"}

// basePackages are installed on every machine, desktop or not.
//
// linux-firmware is deliberately absent. It is a metapackage pulling twelve
// vendor blob sets — nvidia, intel, atheros, mediatek, realtek and the rest —
// which is 277 MB of the base download and about a gigabyte on disk, for
// hardware that does not exist behind QEMU's virt machine. Only board kernels
// such as linux-odroid-n2 depend on it; linux-aarch64 does not, so leaving it
// out really leaves it out.
var basePackages = []string{
	"base", baseKernel,
	"systemd", "sudo", "networkmanager",
	"grub", "efibootmgr", "dosfstools",
	"nano", "vim", "less", "openssh",
	"pciutils", "usbutils", "man-db",
	// Without the keyring the installed system trusts nothing from its own
	// repositories, and every later "pacman -S" fails with "unknown trust".
	"archlinuxarm-keyring",
}

// waylandCommonPackages are the pieces a session needs that are not the
// compositor itself: fonts, portals and XWayland.
var waylandCommonPackages = []string{
	"mesa", "xorg-xwayland",
	"noto-fonts", "noto-fonts-emoji", "ttf-dejavu",
	"xdg-user-dirs", "xdg-desktop-portal-gtk",
	"network-manager-applet",
}

// Script renders the complete unattended installation as a single bash script.
//
// The script is delivered to the guest through Archboot's autorun mechanism
// and runs as root in the live environment. It is deliberately linear and
// fails fast: any error aborts and prints a marker march can detect, rather
// than leaving a half-installed system that looks like it worked.
func Script(p Profile) (string, error) {
	if err := p.Validate(); err != nil {
		return "", err
	}
	p = p.withDefaults()

	var allDesktop []string
	allDesktop = append(allDesktop, waylandCommonPackages...)
	allDesktop = append(allDesktop, hyprlandPackages...)
	// Chrome is not a pacman package, so what it links against has to be asked
	// for by name.
	allDesktop = append(allDesktop, chromePackages...)
	// The general toolset goes in with the desktop rather than the base, so a
	// failure here cannot leave a machine without a bootable base system.
	allDesktop = append(allDesktop, standardPackages...)
	if p.VulkanAccelerated {
		allDesktop = append(allDesktop, vulkanPackages...)
	}
	allDesktop = append(allDesktop, p.ExtraPackages...)

	var b strings.Builder
	w := func(format string, args ...any) {
		fmt.Fprintf(&b, format+"\n", args...)
	}

	w(`#!/bin/bash`)
	w(`# Generated by march. Unattended Arch Linux ARM installation.`)
	w(``)
	// Everything goes to the serial console, which is march's only window into
	// the guest during an unattended run.
	w(`exec >/dev/ttyAMA0 2>&1`)
	w(`set -o pipefail`)
	w(``)
	w(`fail() { echo; echo "%s"; echo "march: failed at line $1"; exit 1; }`, MarkerFailed)
	w(`trap 'fail $LINENO' ERR`)
	w(`set -e`)
	w(`phase() { echo; echo "%s$1==="; }`, MarkerPhase)
	w(``)
	w(`export LANG=C`)
	w(`DISK=%s`, shellQuote(p.Disk))
	w(``)
	// A mirror that has merely slowed down makes pacman's download watchdog
	// give up after ten silent seconds and fail the whole transaction — a
	// slow mirror is worth waiting on in an unattended install, so the
	// timeout is disabled for this run. pacstrap runs pacman against this
	// same config file, so both pacstraps inherit it. A dry run cannot write
	// the host's own config, so the write waits on the file being writable.
	w(`if [ -w /etc/pacman.conf ]; then printf '\nDownloadTimeout = 0\n' >> /etc/pacman.conf; fi`)
	w(``)

	// --- tools -------------------------------------------------------------
	w(`phase %s`, PhaseTools)
	// Arch Linux ARM rotates its build-server signing keys faster than the
	// installer image is rebuilt, so packages routinely arrive signed by a key
	// the live keyring has never seen. pacman then stops on an import prompt
	// that an unattended run cannot answer, and if the keyserver is
	// unreachable it fails outright. Refreshing the keyring first is what
	// keeps that from ending the install.
	w(`pacman -Sy --noconfirm --disable-download-timeout archlinuxarm-keyring || true`)
	w(`pacman-key --populate archlinuxarm >/dev/null 2>&1 || true`)
	w(``)
	w(`# Archboot ships a package database that claims these are installed while`)
	w(`# stripping the binaries out of the image to keep it small. Reinstalling`)
	w(`# without --needed is what actually puts them on disk.`)
	// Reinstalling over files Archboot deleted makes pacman warn once per
	// missing path — thousands of lines that bury anything real. sed drops
	// just that warning; grep is unusable here because it exits non-zero when
	// every line is filtered, which pipefail would turn into a failed install.
	w(`pacman -Sy --noconfirm --disable-download-timeout \`)
	// libarchive and curl are for Chrome, which is not a pacman package and so
	// is fetched and unpacked by hand.
	w(`  arch-install-scripts dosfstools e2fsprogs gptfdisk util-linux coreutils \`)
	w(`  libarchive curl \`)
	w(`  2>&1 | sed '/could not get file information for/d'`)
	w(`for t in pacstrap arch-chroot genfstab sgdisk mkfs.ext4 mkfs.fat bsdtar curl; do`)
	w(`  command -v "$t" >/dev/null || { echo "march: $t is still missing"; exit 1; }`)
	w(`done`)
	w(``)

	// --- partition ---------------------------------------------------------
	w(`phase %s`, PhasePartition)
	w(`sgdisk --zap-all "$DISK"`)
	w(`sgdisk -n1:0:+512M -t1:ef00 -c1:EFI \`)
	w(`       -n2:0:0     -t2:8300 -c2:root "$DISK"`)
	// sgdisk asks the kernel to re-read the table itself; a short settle is
	// enough for the device nodes to appear, and partprobe is not in the image.
	w(`udevadm settle 2>/dev/null || sleep 3`)
	w(`[ -b "${DISK}1" ] && [ -b "${DISK}2" ] || { echo "march: partitions did not appear"; exit 1; }`)
	w(`mkfs.fat -F32 -n EFI "${DISK}1"`)
	w(`mkfs.ext4 -F -q -L root "${DISK}2"`)
	w(``)
	// The ESP is mounted under /boot/efi rather than at /boot, so the kernel
	// and initramfs live on ext4. GRUB then needs no FAT gymnastics and
	// grub-mkconfig can find them whatever they end up being called.
	w(`mount "${DISK}2" /mnt`)
	w(`mkdir -p /mnt/boot/efi`)
	w(`mount "${DISK}1" /mnt/boot/efi`)
	w(``)

	// --- base --------------------------------------------------------------
	w(`phase %s`, PhaseBase)
	w(`pacstrap -K /mnt %s`, strings.Join(basePackages, " "))
	w(``)

	// --- desktop -----------------------------------------------------------
	w(`phase %s`, PhaseDesktop)
	w(`pacstrap /mnt %s`, strings.Join(allDesktop, " "))
	w(``)
	b.WriteString(chromeSnippet())
	w(``)

	// --- configure ---------------------------------------------------------
	w(`phase %s`, PhaseConfigure)
	w(`genfstab -U /mnt >> /mnt/etc/fstab`)
	// Nothing in a running guest reads the ESP — it is written to when GRUB is
	// reinstalled and otherwise ignored — but as a plain fstab entry it sits on
	// the critical path anyway: local-fs.target waits for the partition to
	// appear and be checked, and everything after it, up to the desktop, waits
	// too. That was a second of the boot. As an automount it is mounted on the
	// first access instead, which is the next time somebody touches /boot/efi.
	w(`sed -i -E '\|[[:space:]]/boot/efi[[:space:]]|s|(vfat[[:space:]]+)|\1noauto,x-systemd.automount,|' /mnt/etc/fstab`)
	w(`grep -q 'x-systemd.automount' /mnt/etc/fstab \`)
	w(`  || { echo "march: the ESP entry in fstab was not turned into an automount"; exit 1; }`)
	w(``)
	// The heredoc is quoted so the guest shell sees it verbatim; values are
	// interpolated here, at generation time, already shell-quoted.
	w(`arch-chroot /mnt /bin/bash -s <<'MARCH_CHROOT'`)
	w(`set -e`)
	w(`ln -sf /usr/share/zoneinfo/%s /etc/localtime || ln -sf /usr/share/zoneinfo/UTC /etc/localtime`, p.Timezone)
	w(`hwclock --systohc || true`)
	w(`echo '%s UTF-8' >> /etc/locale.gen`, p.Locale)
	w(`locale-gen`)
	w(`echo 'LANG=%s' > /etc/locale.conf`, p.Locale)
	w(`echo 'KEYMAP=%s' > /etc/vconsole.conf`, p.Keymap)
	w(`echo '%s' > /etc/hostname`, p.Hostname)
	w(`cat > /etc/hosts <<'HOSTS'`)
	w(`127.0.0.1 localhost`)
	w(`::1       localhost`)
	w(`127.0.1.1 %s`, p.Hostname)
	w(`HOSTS`)
	w(``)
	// The desktop's configuration goes into /etc/skel first, so useradd copies
	// it into the new account and the files belong to the user.
	b.WriteString(hyprlandConfigSnippet(p))
	// The launcher goes in with the other /usr/local/bin helpers, and carries
	// the graphics flags this particular guest earned.
	b.WriteString(chromeLauncherSnippet(p))
	b.WriteString(chromeDefaultsSnippet())
	w(``)
	w(`useradd -m -G wheel,video,audio,input -s /bin/bash %s`, shellQuote(p.Username))
	// Without this every docker command needs sudo. The group comes from the
	// docker package, so it is guarded rather than assumed: a missing group
	// should not abort an otherwise good install.
	w(`getent group docker >/dev/null && usermod -aG docker %s || true`, shellQuote(p.Username))
	w(`printf '%%s:%%s\n' %s %s | chpasswd`, shellQuote(p.Username), shellQuote(p.Password))
	w(`printf '%%s:%%s\n' root %s | chpasswd`, shellQuote(p.Password))
	w(`echo '%%wheel ALL=(ALL:ALL) ALL' > /etc/sudoers.d/10-wheel`)
	w(`chmod 0440 /etc/sudoers.d/10-wheel`)
	w(``)
	// pacstrap seeds the target keyring from the live environment, which leaves
	// it without the master signatures that make Arch Linux ARM's build keys
	// trusted. Initialising it here is what lets the finished system install
	// anything at all.
	w(`pacman-key --init >/dev/null 2>&1`)
	w(`pacman-key --populate archlinuxarm >/dev/null 2>&1`)
	w(``)
	w(`systemctl enable NetworkManager`)
	// sshd makes the finished machine reachable on the forwarded port, which is
	// the command march shows on the detail screen.
	w(`systemctl enable sshd`)
	w(`systemctl enable %s`, displayManager)
	w(`systemctl set-default graphical.target`)
	w(``)
	b.WriteString(standardServicesSnippet())
	b.WriteString(bootSnippet())
	b.WriteString(scalingSnippet(p))
	b.WriteString(autologinSnippet(p))
	w(`MARCH_CHROOT`)
	w(``)

	// --- bootloader --------------------------------------------------------
	w(`phase %s`, PhaseBootloader)
	w(`arch-chroot /mnt /bin/bash -s <<'MARCH_BOOT'`)
	w(`set -e`)
	// --removable writes EFI/BOOT/BOOTAA64.EFI, which firmware boots without
	// needing an NVRAM entry to survive.
	w(`grub-install --target=arm64-efi --efi-directory=/boot/efi \`)
	w(`  --bootloader-id=arch --removable --no-nvram`)
	// EDK2 offers its boot menu for five seconds before booting anything, which
	// in a VM is five seconds of nobody pressing anything — and on this display
	// path, five seconds of black window. The timeout is a UEFI variable, so it
	// lives in the machine's own varstore and survives every later boot. It is
	// only settable where efivarfs is mounted, which is the one place this can
	// fail without being worth failing the install over.
	w(`efibootmgr -t 0 >/dev/null 2>&1 || echo "march: could not set the firmware boot timeout"`)
	// An installed VM waits at its GRUB menu only for a keypress that is never
	// going to come — the disk is the only boot target, and a black menu is a
	// worse wait than none. Boot straight through.
	w(`sed -i 's/^GRUB_TIMEOUT=.*/GRUB_TIMEOUT=0/' /etc/default/grub`)
	// The installed system keeps a serial console so march can watch it boot
	// alongside the graphical one. "quiet" is deliberately omitted: for a VM,
	// visible boot progress is worth more than a clean splash, and measuring it
	// showed the log costs nothing — a quiet boot and a verbose one reach the
	// desktop in the same 4.2 seconds.
	w(`sed -i 's|^GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT="console=tty0 console=ttyAMA0,115200"|' /etc/default/grub`)
	// The guest boots without an initramfs, and that is the single largest
	// saving in the whole boot: 2.2 seconds of a 6.4-second one, measured by
	// booting the same disk both ways. An initramfs exists to load the drivers
	// needed to reach the root filesystem, and this kernel has all of them —
	// virtio_blk and ext4 — built in, so the whole phase is a systemd, a udev
	// and a switch-root that find nothing left to do.
	//
	// Everything else it would have carried loads a moment later from the real
	// root instead, which nothing waits on. What it costs is the recovery path:
	// a kernel that could not mount the root now stops rather than dropping to
	// an initramfs shell. march's end-to-end suite installs and boots a real
	// machine, so a kernel that stopped building those drivers in would fail
	// there rather than in front of somebody.
	//
	// root= must then be a device rather than a UUID, since resolving a UUID is
	// itself a job for an initramfs.
	// grub-mkconfig names the initramfs after the kernel, and Arch Linux ARM's
	// kernel is /boot/Image, so it looks for initramfs-Image.img. Removing it
	// makes the choice deliberate rather than a coincidence of naming.
	w(`rm -f /boot/initramfs-Image.img /boot/initramfs-Image-fallback.img`)
	w(`grep -q '^GRUB_DISABLE_LINUX_UUID=' /etc/default/grub \`)
	w(`  && sed -i 's|^GRUB_DISABLE_LINUX_UUID=.*|GRUB_DISABLE_LINUX_UUID=true|' /etc/default/grub \`)
	w(`  || printf 'GRUB_DISABLE_LINUX_UUID=true\n' >> /etc/default/grub`)
	w(`grub-mkconfig -o /boot/grub/grub.cfg`)
	// grub-mkconfig writes a load_video that insmods every video driver GRUB
	// has ever had, including several that arm64-efi does not build. The first
	// one that is missing is an error, and GRUB answers an error inside a menu
	// entry by printing it and waiting ten seconds for a keypress that is never
	// coming — ten seconds of a black window before the kernel is even loaded.
	// Only the drivers this platform actually shipped are left in.
	w(`for m in efi_uga ieee1275_fb vbe vga video_bochs video_cirrus; do`)
	w(`  [ -e "/boot/grub/arm64-efi/$m.mod" ] || sed -i "/^[[:space:]]*insmod $m\$/d" /boot/grub/grub.cfg`)
	w(`done`)
	w(`grep -q 'linux.*/boot/' /boot/grub/grub.cfg || grep -q 'linux\s' /boot/grub/grub.cfg \`)
	w(`  || { echo "march: grub.cfg has no kernel entry"; exit 1; }`)
	w(`grep -q 'linux.*root=/dev/' /boot/grub/grub.cfg \`)
	w(`  || { echo "march: grub.cfg boots by UUID, which needs an initramfs"; exit 1; }`)
	w(`grep -q '^[[:space:]]*initrd' /boot/grub/grub.cfg \`)
	w(`  && { echo "march: grub.cfg loads an initramfs the boot is timed without"; exit 1; }`)
	w(`true`)
	w(`MARCH_BOOT`)
	w(``)
	w(`sync`)
	w(`umount -R /mnt`)
	w(`echo`)
	w(`echo "%s"`, MarkerComplete)

	return b.String(), nil
}

// autologinSnippet configures SDDM to log the user straight in, so the machine
// really does land on a desktop unattended.
func autologinSnippet(p Profile) string {
	if !p.Autologin {
		return ""
	}
	// DisplayServer=wayland is what makes SDDM run the Wayland session script;
	// without it SDDM tries to start X and the autologin silently falls back to
	// a greeter.
	return fmt.Sprintf(`mkdir -p /etc/sddm.conf.d
cat > /etc/sddm.conf.d/autologin.conf <<'SDDM'
[Autologin]
User=%s
Session=%s
[General]
DisplayServer=wayland
SDDM
`, p.Username, sessionName)
}

// standardServicesSnippet turns on the parts of the standard toolset that do
// nothing until they are enabled or configured, and deliberately leaves the
// rest alone. It follows Omarchy's install/config scripts, diverging where a
// virtual machine differs from the laptop they were written for.
func standardServicesSnippet() string {
	var b strings.Builder
	w := func(format string, args ...any) {
		fmt.Fprintf(&b, format+"\n", args...)
	}

	// Enabled, not started: the guest reboots at the end of the install.
	//
	// Everything march installs that has a service has it turned on here. The
	// services Omarchy enables that march does not — avahi, cups-browsed,
	// bluetooth, power-profiles-daemon — are missing because the packages are
	// missing, for the reasons in omittedForVirtualHardware.
	w(`systemctl enable cups.socket`)
	w(`systemctl enable docker.socket`)
	w(`systemctl enable plocate-updatedb.timer`)
	// Ships with kernel-modules-hook.
	w(`systemctl enable linux-modules-cleanup.service`)
	w(``)

	// Omarchy's firewall defaults, plus the one rule march cannot do without:
	// it forwards a host port to the guest's sshd and prints the resulting ssh
	// command on the detail screen. Omarchy has no such forward, so its
	// "default deny incoming" would quietly break a feature march advertises.
	//
	// The rules are written here but applying them is left to the service on
	// first boot: inside the chroot there is no netfilter to load them into,
	// so `ufw enable` reports a failure that says nothing about the installed
	// system.
	w(`ufw default deny incoming || true`)
	w(`ufw default allow outgoing || true`)
	w(`ufw allow 22/tcp || true`)
	w(`sed -i 's/^ENABLED=.*/ENABLED=yes/' /etc/ufw/ufw.conf`)
	w(`systemctl enable ufw.service`)
	w(``)

	return b.String()
}

// scalingSnippet configures the desktop's UI scale.
//
// A guest framebuffer is measured in the host's physical pixels, so on a
// high-density display the desktop renders at native pixel density and
// everything comes out half the size it would be on the host — sharp, but too
// small to read. Scaling the UI back up is what makes the resolution usable
// rather than merely detailed.
func scalingSnippet(p Profile) string {
	scale := p.scaleFactor()
	if scale <= 1 {
		return ""
	}
	// Wayland scales in the compositor. Hyprland's monitor line already carries
	// the factor, and GDK_SCALE on top of it would double-scale every GTK
	// window, so only the XWayland-facing variables are set here.
	return fmt.Sprintf(`cat >> /etc/environment <<'ENVSCALE'
QT_SCALE_FACTOR=%d
XCURSOR_SIZE=%d
ENVSCALE
`, scale, 24*scale)
}

// shellQuote renders a value as a single-quoted shell word, safe to paste into
// the generated script whatever it contains.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
