package install

import (
	"fmt"
	"strings"
)

// Phase is a stage of the installation. The script announces each one on the
// serial console so march can report progress.
type Phase string

const (
	PhaseTools      Phase = "tools"
	PhasePartition  Phase = "partition"
	PhaseBase       Phase = "base"
	PhaseDesktop    Phase = "desktop"
	PhaseConfigure  Phase = "configure"
	PhaseBootloader Phase = "bootloader"
)

// Phases lists the stages in the order the script runs them.
var Phases = []Phase{
	PhaseTools, PhasePartition, PhaseBase, PhaseDesktop, PhaseConfigure, PhaseBootloader,
}

// Label is a human-readable description of a phase.
func (p Phase) Label() string {
	switch p {
	case PhaseTools:
		return "Preparing the installer"
	case PhasePartition:
		return "Partitioning the disk"
	case PhaseBase:
		return "Installing the base system"
	case PhaseDesktop:
		return "Installing the desktop"
	case PhaseConfigure:
		return "Configuring the system"
	case PhaseBootloader:
		return "Installing the bootloader"
	}
	return string(p)
}

// Console markers. march watches for these in the guest's serial output.
const (
	MarkerPhase    = "===MARCH:PHASE:"
	MarkerComplete = "===MARCH:COMPLETE==="
	MarkerFailed   = "===MARCH:FAILED==="
)

// baseKernel is Arch Linux ARM's aarch64 kernel. The plain "linux" package
// does not exist in the ALARM repositories.
const baseKernel = "linux-aarch64"

// vulkanPackages give the guest a Vulkan driver for the virtio GPU. They are
// only installed when the host forwards Vulkan through Venus; without that
// forwarding the driver finds no device and Vulkan programs fail more
// confusingly than if it were simply absent.
//
// This is what gets Chromium off its software rasterizer: the browser renders
// through ANGLE, whose backend is Vulkan, so a guest with GL but no Vulkan
// runs its desktop on the GPU and its web pages on the CPU.
var vulkanPackages = []string{"vulkan-virtio", "vulkan-icd-loader"}

// basePackages are installed on every machine, desktop or not.
var basePackages = []string{
	"base", baseKernel, "linux-firmware",
	"systemd", "sudo", "networkmanager",
	"grub", "efibootmgr", "dosfstools",
	"nano", "vim", "less", "openssh",
	"pciutils", "usbutils", "man-db",
	// Without the keyring the installed system trusts nothing from its own
	// repositories, and every later "pacman -S" fails with "unknown trust".
	"archlinuxarm-keyring",
}

// graphicsPackages give X a working stack. Under QEMU there is no accelerated
// GPU, so Mesa's software renderer does the drawing; the modesetting driver
// picks up virtio-gpu through DRM.
var graphicsPackages = []string{
	"xorg-server", "xorg-xinit", "xorg-xrandr",
	"mesa",
	"noto-fonts", "noto-fonts-emoji", "ttf-dejavu",
	"xdg-user-dirs",
	"network-manager-applet",
}

// waylandCommonPackages are shared by the Wayland desktops: fonts, portals and
// the pieces a session needs that are not the compositor itself.
var waylandCommonPackages = []string{
	"mesa", "xorg-xwayland",
	"noto-fonts", "noto-fonts-emoji", "ttf-dejavu",
	"xdg-user-dirs", "xdg-desktop-portal-gtk",
	"network-manager-applet",
}

// Script renders the complete unattended installation as a single bash script.
//
// The script is delivered to the guest through Archboot's autorun mechanism
// and runs as root in the live environment. It is deliberately linear and
// fails fast: any error aborts and prints a marker march can detect, rather
// than leaving a half-installed system that looks like it worked.
func Script(p Profile) (string, error) {
	if err := p.Validate(); err != nil {
		return "", err
	}
	p = p.withDefaults()

	desktopPkgs, displayManager, session := p.Desktop.packages()
	// The Xorg stack is only meaningful for the X11 desktops; Hyprland is
	// Wayland and pulls XWayland itself.
	var allDesktop []string
	if p.Desktop == DesktopHyprland {
		allDesktop = append(allDesktop, waylandCommonPackages...)
	} else {
		allDesktop = append(allDesktop, graphicsPackages...)
	}
	allDesktop = append(allDesktop, desktopPkgs...)
	if p.VulkanAccelerated {
		allDesktop = append(allDesktop, vulkanPackages...)
	}
	allDesktop = append(allDesktop, p.ExtraPackages...)

	var b strings.Builder
	w := func(format string, args ...any) {
		fmt.Fprintf(&b, format+"\n", args...)
	}

	w(`#!/bin/bash`)
	w(`# Generated by march. Unattended Arch Linux ARM installation.`)
	w(``)
	// Everything goes to the serial console, which is march's only window into
	// the guest during an unattended run.
	w(`exec >/dev/ttyAMA0 2>&1`)
	w(`set -o pipefail`)
	w(``)
	w(`fail() { echo; echo "%s"; echo "march: failed at line $1"; exit 1; }`, MarkerFailed)
	w(`trap 'fail $LINENO' ERR`)
	w(`set -e`)
	w(`phase() { echo; echo "%s$1==="; }`, MarkerPhase)
	w(``)
	w(`export LANG=C`)
	w(`DISK=%s`, shellQuote(p.Disk))
	w(``)

	// --- tools -------------------------------------------------------------
	w(`phase %s`, PhaseTools)
	// Arch Linux ARM rotates its build-server signing keys faster than the
	// installer image is rebuilt, so packages routinely arrive signed by a key
	// the live keyring has never seen. pacman then stops on an import prompt
	// that an unattended run cannot answer, and if the keyserver is
	// unreachable it fails outright. Refreshing the keyring first is what
	// keeps that from ending the install.
	w(`pacman -Sy --noconfirm --disable-download-timeout archlinuxarm-keyring || true`)
	w(`pacman-key --populate archlinuxarm >/dev/null 2>&1 || true`)
	w(``)
	w(`# Archboot ships a package database that claims these are installed while`)
	w(`# stripping the binaries out of the image to keep it small. Reinstalling`)
	w(`# without --needed is what actually puts them on disk.`)
	// Reinstalling over files Archboot deleted makes pacman warn once per
	// missing path — thousands of lines that bury anything real. sed drops
	// just that warning; grep is unusable here because it exits non-zero when
	// every line is filtered, which pipefail would turn into a failed install.
	w(`pacman -Sy --noconfirm --disable-download-timeout \`)
	w(`  arch-install-scripts dosfstools e2fsprogs gptfdisk util-linux coreutils \`)
	w(`  2>&1 | sed '/could not get file information for/d'`)
	w(`for t in pacstrap arch-chroot genfstab sgdisk mkfs.ext4 mkfs.fat; do`)
	w(`  command -v "$t" >/dev/null || { echo "march: $t is still missing"; exit 1; }`)
	w(`done`)
	w(``)

	// --- partition ---------------------------------------------------------
	w(`phase %s`, PhasePartition)
	w(`sgdisk --zap-all "$DISK"`)
	w(`sgdisk -n1:0:+512M -t1:ef00 -c1:EFI \`)
	w(`       -n2:0:0     -t2:8300 -c2:root "$DISK"`)
	// sgdisk asks the kernel to re-read the table itself; a short settle is
	// enough for the device nodes to appear, and partprobe is not in the image.
	w(`udevadm settle 2>/dev/null || sleep 3`)
	w(`[ -b "${DISK}1" ] && [ -b "${DISK}2" ] || { echo "march: partitions did not appear"; exit 1; }`)
	w(`mkfs.fat -F32 -n EFI "${DISK}1"`)
	w(`mkfs.ext4 -F -q -L root "${DISK}2"`)
	w(``)
	// The ESP is mounted under /boot/efi rather than at /boot, so the kernel
	// and initramfs live on ext4. GRUB then needs no FAT gymnastics and
	// grub-mkconfig can find them whatever they end up being called.
	w(`mount "${DISK}2" /mnt`)
	w(`mkdir -p /mnt/boot/efi`)
	w(`mount "${DISK}1" /mnt/boot/efi`)
	w(``)

	// --- base --------------------------------------------------------------
	w(`phase %s`, PhaseBase)
	w(`pacstrap -K /mnt %s`, strings.Join(basePackages, " "))
	w(``)

	// --- desktop -----------------------------------------------------------
	w(`phase %s`, PhaseDesktop)
	w(`pacstrap /mnt %s`, strings.Join(allDesktop, " "))
	w(``)

	// --- configure ---------------------------------------------------------
	w(`phase %s`, PhaseConfigure)
	w(`genfstab -U /mnt >> /mnt/etc/fstab`)
	w(``)
	// The heredoc is quoted so the guest shell sees it verbatim; values are
	// interpolated here, at generation time, already shell-quoted.
	w(`arch-chroot /mnt /bin/bash -s <<'MARCH_CHROOT'`)
	w(`set -e`)
	w(`ln -sf /usr/share/zoneinfo/%s /etc/localtime || ln -sf /usr/share/zoneinfo/UTC /etc/localtime`, p.Timezone)
	w(`hwclock --systohc || true`)
	w(`echo '%s UTF-8' >> /etc/locale.gen`, p.Locale)
	w(`locale-gen`)
	w(`echo 'LANG=%s' > /etc/locale.conf`, p.Locale)
	w(`echo 'KEYMAP=%s' > /etc/vconsole.conf`, p.Keymap)
	w(`echo '%s' > /etc/hostname`, p.Hostname)
	w(`cat > /etc/hosts <<'HOSTS'`)
	w(`127.0.0.1 localhost`)
	w(`::1       localhost`)
	w(`127.0.1.1 %s`, p.Hostname)
	w(`HOSTS`)
	w(``)
	// The desktop's configuration goes into /etc/skel first, so useradd copies
	// it into the new account and the files belong to the user.
	if snippet := desktopConfigSnippet(p); snippet != "" {
		b.WriteString(snippet)
		w(``)
	}
	w(`useradd -m -G wheel,video,audio,input -s /bin/bash %s`, shellQuote(p.Username))
	w(`printf '%%s:%%s\n' %s %s | chpasswd`, shellQuote(p.Username), shellQuote(p.Password))
	w(`printf '%%s:%%s\n' root %s | chpasswd`, shellQuote(p.Password))
	w(`echo '%%wheel ALL=(ALL:ALL) ALL' > /etc/sudoers.d/10-wheel`)
	w(`chmod 0440 /etc/sudoers.d/10-wheel`)
	w(``)
	// pacstrap seeds the target keyring from the live environment, which leaves
	// it without the master signatures that make Arch Linux ARM's build keys
	// trusted. Initialising it here is what lets the finished system install
	// anything at all.
	w(`pacman-key --init >/dev/null 2>&1`)
	w(`pacman-key --populate archlinuxarm >/dev/null 2>&1`)
	w(``)
	// pacstrap builds the initramfs before this point, so it was generated
	// without the console settings written just above and warns about it.
	// Regenerating picks them up.
	w(`mkinitcpio -P 2>&1 | sed -E '/^==> WARNING: (No module containing|architecture)/d'`)
	w(``)
	w(`systemctl enable NetworkManager`)
	// sshd makes the finished machine reachable on the forwarded port, which is
	// the command march shows on the detail screen.
	w(`systemctl enable sshd`)
	w(`systemctl enable %s`, displayManager)
	w(`systemctl set-default graphical.target`)
	w(``)
	b.WriteString(scalingSnippet(p))
	b.WriteString(autologinSnippet(displayManager, session, p))
	b.WriteString(autoResizeSnippet(p))
	w(`MARCH_CHROOT`)
	w(``)

	// --- bootloader --------------------------------------------------------
	w(`phase %s`, PhaseBootloader)
	w(`arch-chroot /mnt /bin/bash -s <<'MARCH_BOOT'`)
	w(`set -e`)
	// --removable writes EFI/BOOT/BOOTAA64.EFI, which firmware boots without
	// needing an NVRAM entry to survive.
	w(`grub-install --target=arm64-efi --efi-directory=/boot/efi \`)
	w(`  --bootloader-id=arch --removable --no-nvram`)
	w(`sed -i 's/^GRUB_TIMEOUT=.*/GRUB_TIMEOUT=1/' /etc/default/grub`)
	// The installed system keeps a serial console so march can watch it boot
	// alongside the graphical one. "quiet" is deliberately omitted: for a VM,
	// visible boot progress is worth more than a clean splash, and it gives
	// march a reliable signal that the desktop has come up.
	w(`sed -i 's|^GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT="console=tty0 console=ttyAMA0,115200"|' /etc/default/grub`)
	w(`grub-mkconfig -o /boot/grub/grub.cfg`)
	w(`grep -q 'linux.*/boot/' /boot/grub/grub.cfg || grep -q 'linux\s' /boot/grub/grub.cfg \`)
	w(`  || { echo "march: grub.cfg has no kernel entry"; exit 1; }`)
	w(`MARCH_BOOT`)
	w(``)
	w(`sync`)
	w(`umount -R /mnt`)
	w(`echo`)
	w(`echo "%s"`, MarkerComplete)

	return b.String(), nil
}

// autologinSnippet configures the display manager to log the user straight in,
// so the machine really does land on a desktop unattended. Each display
// manager has its own mechanism.
func autologinSnippet(displayManager, session string, p Profile) string {
	if !p.Autologin {
		return ""
	}
	user := shellQuote(p.Username)

	switch displayManager {
	case "gdm":
		// GDM has no drop-in directory, so its config is edited in place: the
		// autologin keys are inserted under [daemon] and the rest of the file
		// is left alone.
		return fmt.Sprintf(`mkdir -p /etc/gdm
touch /etc/gdm/custom.conf
grep -q '^\[daemon\]' /etc/gdm/custom.conf || printf '[daemon]\n' >> /etc/gdm/custom.conf
sed -i '/^AutomaticLogin/d' /etc/gdm/custom.conf
sed -i '0,/^\[daemon\]/s//[daemon]\nAutomaticLoginEnable=True\nAutomaticLogin=%s/' /etc/gdm/custom.conf
`, p.Username)

	case "sddm":
		// DisplayServer=wayland is what makes SDDM run the Wayland session
		// script; without it SDDM tries to start X and the autologin silently
		// falls back to a greeter.
		return fmt.Sprintf(`mkdir -p /etc/sddm.conf.d
cat > /etc/sddm.conf.d/autologin.conf <<'SDDM'
[Autologin]
User=%s
Session=%s
[General]
DisplayServer=wayland
SDDM
`, p.Username, session)

	default: // lightdm
		// LightDM requires the account to be in an "autologin" group, which
		// does not exist until it is created.
		//
		// The settings go in a drop-in rather than lightdm.conf itself. Arch's
		// lightdm.conf carries session-wrapper=/etc/lightdm/Xsession, and
		// overwriting it leaves LightDM using its compiled-in default wrapper,
		// which does not exist on Arch — the session then dies instantly and
		// LightDM silently falls back to showing the greeter.
		return fmt.Sprintf(`groupadd -r autologin 2>/dev/null || true
gpasswd -a %s autologin
mkdir -p /etc/lightdm/lightdm.conf.d
cat > /etc/lightdm/lightdm.conf.d/50-march-autologin.conf <<'LIGHTDM'
[Seat:*]
autologin-user=%s
autologin-session=%s
autologin-user-timeout=0
LIGHTDM
`, user, p.Username, session)
	}
}

// desktopConfigSnippet writes any desktop-specific configuration into
// /etc/skel, ahead of the account being created.
func desktopConfigSnippet(p Profile) string {
	if p.Desktop == DesktopHyprland {
		return hyprlandConfigSnippet(p)
	}
	return ""
}

// scalingSnippet configures the desktop's UI scale.
//
// A guest framebuffer is measured in the host's physical pixels, so on a
// high-density display the desktop renders at native pixel density and
// everything comes out half the size it would be on the host — sharp, but too
// small to read. Scaling the UI back up is what makes the resolution usable
// rather than merely detailed.
func scalingSnippet(p Profile) string {
	scale := p.scaleFactor()
	if scale <= 1 {
		return ""
	}
	// Wayland scales in the compositor. Hyprland's monitor line already carries
	// the factor, and GDK_SCALE on top of it would double-scale every GTK
	// window, so only the XWayland-facing variables are set here.
	if p.Desktop == DesktopHyprland {
		return fmt.Sprintf(`cat >> /etc/environment <<'ENVSCALE'
QT_SCALE_FACTOR=%d
XCURSOR_SIZE=%d
ENVSCALE
`, scale, 24*scale)
	}
	dpi := 96 * scale
	cursor := 24 * scale

	var b strings.Builder
	// Environment variables reach every toolkit and are read by PAM for login
	// sessions, so they cover the display manager's session too.
	fmt.Fprintf(&b, `cat >> /etc/environment <<'ENVSCALE'
GDK_SCALE=%d
QT_SCALE_FACTOR=%d
XCURSOR_SIZE=%d
ENVSCALE
`, scale, scale, cursor)

	// XFCE's settings daemon publishes its own XSETTINGS, which override the
	// environment for anything started inside the session.
	fmt.Fprintf(&b, `mkdir -p /etc/xdg/xfce4/xfconf/xfce-perchannel-xml
cat > /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml <<'XSETTINGS'
<?xml version="1.0" encoding="UTF-8"?>
<channel name="xsettings" version="1.0">
  <property name="Gdk" type="empty">
    <property name="WindowScalingFactor" type="int" value="%d"/>
  </property>
  <property name="Gtk" type="empty">
    <property name="CursorThemeSize" type="int" value="%d"/>
  </property>
</channel>
XSETTINGS
`, scale, cursor)

	// The greeter runs before any session, so it needs telling separately.
	fmt.Fprintf(&b, `if [ -f /etc/lightdm/lightdm-gtk-greeter.conf ]; then
  sed -i '/^xft-dpi=/d' /etc/lightdm/lightdm-gtk-greeter.conf
  printf 'xft-dpi=%d
' >> /etc/lightdm/lightdm-gtk-greeter.conf
fi
`, dpi)

	// X clients that predate XSETTINGS read their font DPI from the server.
	fmt.Fprintf(&b, `mkdir -p /etc/X11/xinit/xinitrc.d
cat > /etc/X11/xinit/xinitrc.d/95-march-scaling.sh <<'XRES'
#!/bin/sh
xrandr --dpi %d 2>/dev/null || true
XRES
chmod 0755 /etc/X11/xinit/xinitrc.d/95-march-scaling.sh
`, dpi)

	return b.String()
}

// autoResizeSnippet installs a helper that keeps the guest's resolution in step
// with the host window.
//
// When the QEMU window is resized, virtio-gpu reports a new preferred mode to
// the guest. The kernel picks it up, but X does not switch to it on its own —
// GNOME and KDE handle that in their compositors, while a plain X session like
// XFCE needs something to notice and apply it. This is the guest half of
// window resizing; without it the display stays at its boot resolution and the
// window merely scales.
func autoResizeSnippet(p Profile) string {
	// Only useful when the host window dictates the guest's size. Otherwise
	// the guest owns its resolution and the helper would keep overriding it.
	if !p.FollowHostResize {
		return ""
	}
	// GNOME and KDE already track display changes; a second agent fighting
	// them would only cause flicker.
	if p.Desktop != DesktopXFCE {
		return ""
	}
	return `cat > /usr/local/bin/march-autoresize <<'RESIZE'
#!/bin/sh
# Follow the host window: apply the preferred mode whenever it is not active.
# xrandr marks the preferred mode with "+" and the active one with "*".
while :; do
  out=$(xrandr --query 2>/dev/null | awk '/ connected/{print $1; exit}')
  if [ -n "$out" ] && xrandr --query 2>/dev/null |
       grep -qE '^[[:space:]]+[0-9]+x[0-9]+.*\+' &&
     ! xrandr --query 2>/dev/null |
       grep -qE '^[[:space:]]+[0-9]+x[0-9]+.*\*\+'; then
    xrandr --output "$out" --auto 2>/dev/null
  fi
  sleep 2
done
RESIZE
chmod 0755 /usr/local/bin/march-autoresize
mkdir -p /etc/xdg/autostart
cat > /etc/xdg/autostart/march-autoresize.desktop <<'DESKTOP'
[Desktop Entry]
Type=Application
Name=march display auto-resize
Exec=/usr/local/bin/march-autoresize
NoDisplay=true
OnlyShowIn=XFCE;
DESKTOP
`
}

// shellQuote renders a value as a single-quoted shell word, safe to paste into
// the generated script whatever it contains.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
